version: '3.7'
services:
  nuxt.js:
    container_name: nuxt.js
    build:
      context: ./docker/nuxt.js
      dockerfile: Dockerfile
    ports:
      - 3000:3000
    volumes:
      - ./docker/nuxt.js/src:/src:cached
      # exclude volumes
      - /src/app/node_modules
    tty: true
    stdin_open: true
  postgres:
    container_name: postgres
    build:
      context: ./docker/postgres
      dockerfile: Dockerfile
    environment:
      - POSTGRES_USER=gopher
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=go_db
  golang:
    container_name: golang
    depends_on:
      - postgres
    build:
      context: ./docker/golang
      dockerfile: Dockerfile
    ports:
      - "1323:1323"
    volumes:
      - ./docker/golang/api:/go/src/api
    command: realize start
