settings:
  legacy:
    force: false
    interval: 0s
schema:
- name: api
  path: .
  commands:
    install:
      status: true
      method: go build -o app.out /go/src/api/main.go
    run:
      status: true
      method: ./app.out
  watcher:
    extensions:
    - go
    paths:
    - /
    ignore:
      paths:
      - .git
      - .realize
      - vendor
